# Generated by Django 5.1.4 on 2025-01-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_viewer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileviewer',
            name='username',
        ),
        migrations.AddField(
            model_name='profileviewer',
            name='viewer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileviewer',
            name='viewername',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileviewer',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
