# Generated by Django 5.1.4 on 2025-01-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_viewer_app', '0002_remove_profileviewer_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileviewer',
            name='picture_file',
            field=models.FileField(blank=True, null=True, upload_to='picture'),
        ),
    ]
