# Generated by Django 5.1.4 on 2025-01-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_viewer_app', '0004_profileviewer_picture_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileviewer',
            name='picture_id',
        ),
        migrations.AlterField(
            model_name='profileviewer',
            name='picture_file',
            field=models.CharField(max_length=100),
        ),
    ]
