# Generated by Django 5.1.4 on 2025-01-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_alter_video_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='titel_picture_file',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
